### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by LiquidsINSILICO** [wesbarnett/thermint#1]
-- Could NOT find Boost
CMake Error at CMakeLists.txt:13 (message):
  Could not find Boost.

-- Configuring incomplete, errors occurred!
See also "/home/anu/Desktop/anupama/work/peptide_study/thermint-master/build/CMakeFiles/CMakeOutput.log".

I came across the above error mentioned during installation....
Could you please help regarding the error.

**Comment by wesbarnett** [comment]
Sorry it's been several years since I've touched this
